CREATE TABLE Person(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       username varchar(100) NOT NULL,
                       email varchar NOT NULL,
                       password varchar NOT NULL
);

CREATE TABLE Notes(
                      id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      person_id int REFERENCES Person(id) ON DELETE CASCADE,
                      notes_name varchar(100) NOT NULL,
                      description varchar(100) NOT NULL,
                      timeanddate date NOT NULL,
                      createdate date NOT NULL
);

CREATE TABLE Trash(
                      id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      person_id int NOT NULL,
                      notes_name varchar(100) NOT NULL,
                      description varchar(100) NOT NULL,
                      timeanddate date NOT NULL,
                      createdate date NOT NULL
);

CREATE TABLE Comment(
                        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        notes_id int REFERENCES Notes(id) ON DELETE CASCADE,
                        comments varchar(100) NOT NULL
);
